# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cordfm' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'CameraKit-iOS'
  pod 'SwiftyJSON'
  pod 'NotificationBannerSwift', '~> 3.0.0'

  # Pods for Cordfm

end
